### your site title here

title: Your Name
description: subtitle | affiliations | motto

baseurl: / #name of GitHub repository
url: https://matheger.github.io #custom url to be used instead of GitHub repository
email: #

#highlighter: pandoc # pandoc is not supported by github pages
highlighter: rouge
markdown: kramdown

# Markdown Processors
#kramdown:
#  input: GFM
#  auto_ids: true
#  syntax_highlighter: rouge
  
#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-email-protect
  - jekyll-target-blank
